name: Export Configuration

on:
  workflow_dispatch:

jobs:
  build:
    name: Export Encrypted Configuration
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT }}

      - name: Set Up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Export Configuration
        env:
            INSPECT_WECHAT_HOOK_KEY: ${{ secrets.INSPECT_WECHAT_HOOK_KEY }}
            INSPECT_TELEGRAM_BOT_TOKEN: ${{ secrets.INSPECT_TELEGRAM_BOT_TOKEN }}
            INSPECT_TELEGRAM_CHAT_ID: ${{ secrets.INSPECT_TELEGRAM_CHAT_ID }}
            INSPECT_AES_KEY: ${{ secrets.INSPECT_AES_KEY }}
            CONFIG: ${{ secrets.CONFIG }}
            AES_KEY: ${{ secrets.AES_KEY }}
            PAT: ${{ secrets.PAT }}
        run: |
          pip3 install -r requirements.txt
          python3 inspect_configs.py
