name: Star Watcher

on:
  watch:
    types: started

jobs:
  build:
    name: Log New Star
    runs-on: ubuntu-latest
    steps:
      - name: Log New Star
        run: |
          TZ=Asia/Shanghai date "+%y-%m-%d %H:%M:%S" | xargs -I {} echo "[{}] Repository received a star"